version: '3.7'

services:

  influxdb:
    build: influxdb
    privileged: true
    volumes:
        - 'influxdb-data:/mnt/influxdb'
    labels:
      org.label-schema.group: "chordx_infra"
    
  telegraf:
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    labels:
      org.label-schema.group: "chordx_infra"

  grafana:
    build: grafana 
    depends_on:
       - influxdb
    labels:
      org.label-schema.group: "chordx_infra"

  nginx:
    build: nginx
    #volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    labels:
      org.label-schema.group: "chordx_infra"

  api:
    image: chordx_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    labels:
      org.label-schema.group: "chordx_api"

  

volumes:
    influxdb-data:

